### PR TITLE
Deprecation fix for using targetObject

### PR DESCRIPTION
**Pull request by malatin3**
Wasn't sure if I should change the readme at all to mention linkTarget.

### CODE REVIEW

**Comment by asross** [comment]
Hey, thanks for the PR! Unfortunately it looks like this actually breaks the action functionality, according to Travis:
image
Definitely want to fix that :) I'll also try to take a look in the next day or two if I have time!

**Comment by malatin3** [comment]
Hmm, this passed locally with the added conditional. It seems like something weird may have happened. How do I retrigger the tests? haha

**Comment by asross** [comment]
You could push an additional meaningless commit (like add an extra space)
and see what happens :)

**Comment by asross** [comment]
Apologies about the delay in approving this. The flakiness is weird, but maybe it's just Travis!

To verify everything was working ok, I ran the tests locally, and they passed as well, but I did notice that I was still getting the deprecation warning on tests that use actions (when running `ember try:one ember-release test`):

image

image

I did google around a little bit, and from that I discovered that if we replace `this.get('targetObject') || this.get('_targetObject')` with `this.get('_targetObject') || this.get('targetObject')`, the warning goes away. But I'm kind of confused why we even reach that codepath in the first place, because I'd expect `this.get('target')` to return something.

Anyway, if you have any thoughts, let me know. A quick fix would just be to do what I suggested above, but it would be nice to really get it right :)

**Comment by malatin3** [comment]
Hmm.. I tried looking into it also but I couldn't really find any super conclusive results.

In [this issue](https://github.com/emberjs/ember.js/issues/14168) they talk about how they originally intended targetObject to be a write only API where you pass in a value if you want to set it but did not plan on having people read it for the default value. Maybe they used a similar approach with target where it wouldn't be available for reading by default?

Maybe rolling back my changes and just flipping the targetObject || _targetObject to prefer the private API is the simplest solution? It seems Ember is generally moving towards closure actions instead of the old style with send.. so maybe there is also a solution there? Though, I'm not sure how easy it would be to maintain the current functionality if we switched.

**Comment by asross** [comment]
> Hmm.. I tried looking into it also but I couldn't really find any super conclusive results.

Yeah, it seemed tough to me too. Thanks for doing the research though!

> Maybe rolling back my changes and just flipping the targetObject || _targetObject to prefer the private API is the simplest solution?

SGTM!

> It seems Ember is generally moving towards closure actions instead of the old style with send.. so maybe there is also a solution there? Though, I'm not sure how easy it would be to maintain the current functionality if we switched.

At _some_ point we'll probably need to make a backwards-incompatible change, but I'd like to delay it as long as possible :)

**Pull request closed without merging**
